import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :video_generator, VideoGeneratorWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: VideoGenerator.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.

config :video_generator,
       :node_name,
       System.get_env("NODE_NAME") || :"video_generator@#{:inet.gethostname()}"

config :libcluster,
  topologies: [
    k8s: [
      strategy: Cluster.Strategy.Epmd,
      config: [
        hosts: [
          :"video_generator@WHITE-BEAST"
        ]
      ]
    ]
  ]
